// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBackendAPI.Data;

#nullable disable

namespace MyBackendAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260712184734_UpdateSubjects")]
    partial class UpdateSubjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyBackendAPI.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<bool>("IsGradeLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Grade = 10,
                            IsGradeLocked = false,
                            Name = "10A"
                        },
                        new
                        {
                            Id = 2,
                            Grade = 10,
                            IsGradeLocked = false,
                            Name = "10A01"
                        },
                        new
                        {
                            Id = 3,
                            Grade = 10,
                            IsGradeLocked = false,
                            Name = "10D"
                        },
                        new
                        {
                            Id = 4,
                            Grade = 11,
                            IsGradeLocked = false,
                            Name = "11A"
                        },
                        new
                        {
                            Id = 5,
                            Grade = 11,
                            IsGradeLocked = false,
                            Name = "11A01"
                        },
                        new
                        {
                            Id = 6,
                            Grade = 11,
                            IsGradeLocked = false,
                            Name = "11D"
                        },
                        new
                        {
                            Id = 7,
                            Grade = 12,
                            IsGradeLocked = false,
                            Name = "12A"
                        },
                        new
                        {
                            Id = 8,
                            Grade = 12,
                            IsGradeLocked = false,
                            Name = "12A01"
                        },
                        new
                        {
                            Id = 9,
                            Grade = 12,
                            IsGradeLocked = false,
                            Name = "12D"
                        });
                });

            modelBuilder.Entity("MyBackendAPI.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("AttendanceScore")
                        .HasColumnType("float");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<double?>("FifteenMinScore1")
                        .HasColumnType("float");

                    b.Property<double?>("FifteenMinScore2")
                        .HasColumnType("float");

                    b.Property<double?>("FinalScore")
                        .HasColumnType("float");

                    b.Property<double?>("MidtermScore")
                        .HasColumnType("float");

                    b.Property<double?>("OralScore1")
                        .HasColumnType("float");

                    b.Property<double?>("OralScore2")
                        .HasColumnType("float");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcademicYear = "2023-2024",
                            AttendanceScore = 10.0,
                            ClassId = 1,
                            FifteenMinScore1 = 7.5,
                            FifteenMinScore2 = 8.5,
                            FinalScore = 9.0,
                            MidtermScore = 8.0,
                            OralScore1 = 8.0,
                            OralScore2 = 9.0,
                            Semester = 1,
                            StudentId = 3,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            AcademicYear = "2023-2024",
                            AttendanceScore = 9.0,
                            ClassId = 1,
                            FifteenMinScore1 = 8.0,
                            FifteenMinScore2 = 7.0,
                            FinalScore = 8.0,
                            MidtermScore = 7.5,
                            OralScore1 = 7.0,
                            OralScore2 = 8.0,
                            Semester = 1,
                            StudentId = 4,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 3,
                            AcademicYear = "2023-2024",
                            AttendanceScore = 10.0,
                            ClassId = 1,
                            FifteenMinScore1 = 9.0,
                            FifteenMinScore2 = 9.5,
                            FinalScore = 9.5,
                            MidtermScore = 9.5,
                            OralScore1 = 10.0,
                            OralScore2 = 10.0,
                            Semester = 1,
                            StudentId = 5,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 4,
                            AcademicYear = "2023-2024",
                            AttendanceScore = 9.0,
                            ClassId = 1,
                            FifteenMinScore1 = 8.5,
                            FifteenMinScore2 = 8.5,
                            FinalScore = 8.5,
                            MidtermScore = 9.0,
                            OralScore1 = 9.0,
                            OralScore2 = 9.0,
                            Semester = 2,
                            StudentId = 3,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 5,
                            AcademicYear = "2023-2024",
                            AttendanceScore = 10.0,
                            ClassId = 1,
                            FifteenMinScore1 = 7.0,
                            FifteenMinScore2 = 8.0,
                            FinalScore = 8.5,
                            MidtermScore = 8.0,
                            OralScore1 = 8.0,
                            OralScore2 = 8.0,
                            Semester = 2,
                            StudentId = 4,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 6,
                            AcademicYear = "2023-2024",
                            AttendanceScore = 10.0,
                            ClassId = 1,
                            FifteenMinScore1 = 10.0,
                            FifteenMinScore2 = 10.0,
                            FinalScore = 9.0,
                            MidtermScore = 9.0,
                            OralScore1 = 9.0,
                            OralScore2 = 10.0,
                            Semester = 2,
                            StudentId = 5,
                            SubjectId = 1
                        });
                });

            modelBuilder.Entity("MyBackendAPI.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RelatedRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MyBackendAPI.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Student"
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "Teacher"
                        });
                });

            modelBuilder.Entity("MyBackendAPI.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A101"
                        },
                        new
                        {
                            Id = 2,
                            Name = "A102"
                        },
                        new
                        {
                            Id = 3,
                            Name = "B204"
                        });
                });

            modelBuilder.Entity("MyBackendAPI.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("ClassSize")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("Slot")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("RoomId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            ClassSize = 30,
                            Date = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 1,
                            Slot = 1,
                            Status = "PRESENT",
                            SubjectCode = "TOAN 10",
                            TeacherId = 100
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 1,
                            ClassSize = 30,
                            Date = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 1,
                            Slot = 2,
                            Status = "PRESENT",
                            SubjectCode = "TOAN 10",
                            TeacherId = 100
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 1,
                            ClassSize = 30,
                            Date = new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 1,
                            Slot = 1,
                            Status = "FUTURE",
                            SubjectCode = "TOAN 10",
                            TeacherId = 100
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 1,
                            ClassSize = 30,
                            Date = new DateTime(2026, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 3,
                            Slot = 4,
                            Status = "FUTURE",
                            SubjectCode = "TOAN 10",
                            TeacherId = 100
                        });
                });

            modelBuilder.Entity("MyBackendAPI.Models.ScheduleRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MakeUpDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MakeUpSlot")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("TeacherId");

                    b.ToTable("ScheduleRequests");
                });

            modelBuilder.Entity("MyBackendAPI.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "TOAN 10",
                            Grade = 10,
                            Group = "Bắt buộc",
                            Name = "Toán"
                        },
                        new
                        {
                            Id = 2,
                            Code = "NV 10",
                            Grade = 10,
                            Group = "Bắt buộc",
                            Name = "Ngữ văn"
                        },
                        new
                        {
                            Id = 3,
                            Code = "NN1 10",
                            Grade = 10,
                            Group = "Bắt buộc",
                            Name = "Ngoại ngữ 1 (Tiếng Anh)"
                        },
                        new
                        {
                            Id = 4,
                            Code = "LS 10",
                            Grade = 10,
                            Group = "Bắt buộc",
                            Name = "Lịch sử"
                        },
                        new
                        {
                            Id = 5,
                            Code = "GDTC 10",
                            Grade = 10,
                            Group = "Bắt buộc",
                            Name = "Giáo dục Thể chất"
                        },
                        new
                        {
                            Id = 6,
                            Code = "GDQPAN 10",
                            Grade = 10,
                            Group = "Bắt buộc",
                            Name = "Giáo dục Quốc phòng và An ninh"
                        },
                        new
                        {
                            Id = 7,
                            Code = "VL 10",
                            Grade = 10,
                            Group = "Lựa chọn (Tự nhiên)",
                            Name = "Vật lý"
                        },
                        new
                        {
                            Id = 8,
                            Code = "HH 10",
                            Grade = 10,
                            Group = "Lựa chọn (Tự nhiên)",
                            Name = "Hóa học"
                        },
                        new
                        {
                            Id = 9,
                            Code = "SH 10",
                            Grade = 10,
                            Group = "Lựa chọn (Tự nhiên)",
                            Name = "Sinh học"
                        },
                        new
                        {
                            Id = 10,
                            Code = "DL 10",
                            Grade = 10,
                            Group = "Lựa chọn (Xã hội)",
                            Name = "Địa lý"
                        },
                        new
                        {
                            Id = 11,
                            Code = "GDKTPL 10",
                            Grade = 10,
                            Group = "Lựa chọn (Xã hội)",
                            Name = "Giáo dục kinh tế và pháp luật"
                        },
                        new
                        {
                            Id = 12,
                            Code = "TH 10",
                            Grade = 10,
                            Group = "Lựa chọn (Công nghệ & Nghệ thuật)",
                            Name = "Tin học"
                        },
                        new
                        {
                            Id = 13,
                            Code = "CN 10",
                            Grade = 10,
                            Group = "Lựa chọn (Công nghệ & Nghệ thuật)",
                            Name = "Công nghệ"
                        },
                        new
                        {
                            Id = 14,
                            Code = "AN 10",
                            Grade = 10,
                            Group = "Lựa chọn (Công nghệ & Nghệ thuật)",
                            Name = "Âm nhạc"
                        },
                        new
                        {
                            Id = 15,
                            Code = "MT 10",
                            Grade = 10,
                            Group = "Lựa chọn (Công nghệ & Nghệ thuật)",
                            Name = "Mỹ thuật"
                        },
                        new
                        {
                            Id = 16,
                            Code = "TOAN 11",
                            Grade = 11,
                            Group = "Bắt buộc",
                            Name = "Toán"
                        },
                        new
                        {
                            Id = 17,
                            Code = "NV 11",
                            Grade = 11,
                            Group = "Bắt buộc",
                            Name = "Ngữ văn"
                        },
                        new
                        {
                            Id = 18,
                            Code = "NN1 11",
                            Grade = 11,
                            Group = "Bắt buộc",
                            Name = "Ngoại ngữ 1 (Tiếng Anh)"
                        },
                        new
                        {
                            Id = 19,
                            Code = "LS 11",
                            Grade = 11,
                            Group = "Bắt buộc",
                            Name = "Lịch sử"
                        },
                        new
                        {
                            Id = 20,
                            Code = "GDTC 11",
                            Grade = 11,
                            Group = "Bắt buộc",
                            Name = "Giáo dục Thể chất"
                        },
                        new
                        {
                            Id = 21,
                            Code = "GDQPAN 11",
                            Grade = 11,
                            Group = "Bắt buộc",
                            Name = "Giáo dục Quốc phòng và An ninh"
                        },
                        new
                        {
                            Id = 22,
                            Code = "VL 11",
                            Grade = 11,
                            Group = "Lựa chọn (Tự nhiên)",
                            Name = "Vật lý"
                        },
                        new
                        {
                            Id = 23,
                            Code = "HH 11",
                            Grade = 11,
                            Group = "Lựa chọn (Tự nhiên)",
                            Name = "Hóa học"
                        },
                        new
                        {
                            Id = 24,
                            Code = "SH 11",
                            Grade = 11,
                            Group = "Lựa chọn (Tự nhiên)",
                            Name = "Sinh học"
                        },
                        new
                        {
                            Id = 25,
                            Code = "DL 11",
                            Grade = 11,
                            Group = "Lựa chọn (Xã hội)",
                            Name = "Địa lý"
                        },
                        new
                        {
                            Id = 26,
                            Code = "GDKTPL 11",
                            Grade = 11,
                            Group = "Lựa chọn (Xã hội)",
                            Name = "Giáo dục kinh tế và pháp luật"
                        },
                        new
                        {
                            Id = 27,
                            Code = "TH 11",
                            Grade = 11,
                            Group = "Lựa chọn (Công nghệ & Nghệ thuật)",
                            Name = "Tin học"
                        },
                        new
                        {
                            Id = 28,
                            Code = "CN 11",
                            Grade = 11,
                            Group = "Lựa chọn (Công nghệ & Nghệ thuật)",
                            Name = "Công nghệ"
                        },
                        new
                        {
                            Id = 29,
                            Code = "AN 11",
                            Grade = 11,
                            Group = "Lựa chọn (Công nghệ & Nghệ thuật)",
                            Name = "Âm nhạc"
                        },
                        new
                        {
                            Id = 30,
                            Code = "MT 11",
                            Grade = 11,
                            Group = "Lựa chọn (Công nghệ & Nghệ thuật)",
                            Name = "Mỹ thuật"
                        },
                        new
                        {
                            Id = 31,
                            Code = "TOAN 12",
                            Grade = 12,
                            Group = "Bắt buộc",
                            Name = "Toán"
                        },
                        new
                        {
                            Id = 32,
                            Code = "NV 12",
                            Grade = 12,
                            Group = "Bắt buộc",
                            Name = "Ngữ văn"
                        },
                        new
                        {
                            Id = 33,
                            Code = "NN1 12",
                            Grade = 12,
                            Group = "Bắt buộc",
                            Name = "Ngoại ngữ 1 (Tiếng Anh)"
                        },
                        new
                        {
                            Id = 34,
                            Code = "LS 12",
                            Grade = 12,
                            Group = "Bắt buộc",
                            Name = "Lịch sử"
                        },
                        new
                        {
                            Id = 35,
                            Code = "GDTC 12",
                            Grade = 12,
                            Group = "Bắt buộc",
                            Name = "Giáo dục Thể chất"
                        },
                        new
                        {
                            Id = 36,
                            Code = "GDQPAN 12",
                            Grade = 12,
                            Group = "Bắt buộc",
                            Name = "Giáo dục Quốc phòng và An ninh"
                        },
                        new
                        {
                            Id = 37,
                            Code = "VL 12",
                            Grade = 12,
                            Group = "Lựa chọn (Tự nhiên)",
                            Name = "Vật lý"
                        },
                        new
                        {
                            Id = 38,
                            Code = "HH 12",
                            Grade = 12,
                            Group = "Lựa chọn (Tự nhiên)",
                            Name = "Hóa học"
                        },
                        new
                        {
                            Id = 39,
                            Code = "SH 12",
                            Grade = 12,
                            Group = "Lựa chọn (Tự nhiên)",
                            Name = "Sinh học"
                        },
                        new
                        {
                            Id = 40,
                            Code = "DL 12",
                            Grade = 12,
                            Group = "Lựa chọn (Xã hội)",
                            Name = "Địa lý"
                        },
                        new
                        {
                            Id = 41,
                            Code = "GDKTPL 12",
                            Grade = 12,
                            Group = "Lựa chọn (Xã hội)",
                            Name = "Giáo dục kinh tế và pháp luật"
                        },
                        new
                        {
                            Id = 42,
                            Code = "TH 12",
                            Grade = 12,
                            Group = "Lựa chọn (Công nghệ & Nghệ thuật)",
                            Name = "Tin học"
                        },
                        new
                        {
                            Id = 43,
                            Code = "CN 12",
                            Grade = 12,
                            Group = "Lựa chọn (Công nghệ & Nghệ thuật)",
                            Name = "Công nghệ"
                        },
                        new
                        {
                            Id = 44,
                            Code = "AN 12",
                            Grade = 12,
                            Group = "Lựa chọn (Công nghệ & Nghệ thuật)",
                            Name = "Âm nhạc"
                        },
                        new
                        {
                            Id = 45,
                            Code = "MT 12",
                            Grade = 12,
                            Group = "Lựa chọn (Công nghệ & Nghệ thuật)",
                            Name = "Mỹ thuật"
                        });
                });

            modelBuilder.Entity("MyBackendAPI.Models.TeacherSubject", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("TeacherSubjects");

                    b.HasData(
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 1
                        },
                        new
                        {
                            TeacherId = 103,
                            SubjectId = 1
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 2
                        },
                        new
                        {
                            TeacherId = 103,
                            SubjectId = 2
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 3
                        },
                        new
                        {
                            TeacherId = 103,
                            SubjectId = 3
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 4
                        },
                        new
                        {
                            TeacherId = 103,
                            SubjectId = 4
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 5
                        },
                        new
                        {
                            TeacherId = 103,
                            SubjectId = 5
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 6
                        },
                        new
                        {
                            TeacherId = 103,
                            SubjectId = 6
                        },
                        new
                        {
                            TeacherId = 101,
                            SubjectId = 7
                        },
                        new
                        {
                            TeacherId = 103,
                            SubjectId = 7
                        },
                        new
                        {
                            TeacherId = 101,
                            SubjectId = 8
                        },
                        new
                        {
                            TeacherId = 103,
                            SubjectId = 8
                        },
                        new
                        {
                            TeacherId = 101,
                            SubjectId = 9
                        },
                        new
                        {
                            TeacherId = 103,
                            SubjectId = 9
                        },
                        new
                        {
                            TeacherId = 102,
                            SubjectId = 10
                        },
                        new
                        {
                            TeacherId = 103,
                            SubjectId = 10
                        },
                        new
                        {
                            TeacherId = 102,
                            SubjectId = 11
                        },
                        new
                        {
                            TeacherId = 103,
                            SubjectId = 11
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 12
                        },
                        new
                        {
                            TeacherId = 103,
                            SubjectId = 12
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 13
                        },
                        new
                        {
                            TeacherId = 103,
                            SubjectId = 13
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 14
                        },
                        new
                        {
                            TeacherId = 103,
                            SubjectId = 14
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 15
                        },
                        new
                        {
                            TeacherId = 103,
                            SubjectId = 15
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 16
                        },
                        new
                        {
                            TeacherId = 104,
                            SubjectId = 16
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 17
                        },
                        new
                        {
                            TeacherId = 104,
                            SubjectId = 17
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 18
                        },
                        new
                        {
                            TeacherId = 104,
                            SubjectId = 18
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 19
                        },
                        new
                        {
                            TeacherId = 104,
                            SubjectId = 19
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 20
                        },
                        new
                        {
                            TeacherId = 104,
                            SubjectId = 20
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 21
                        },
                        new
                        {
                            TeacherId = 104,
                            SubjectId = 21
                        },
                        new
                        {
                            TeacherId = 101,
                            SubjectId = 22
                        },
                        new
                        {
                            TeacherId = 104,
                            SubjectId = 22
                        },
                        new
                        {
                            TeacherId = 101,
                            SubjectId = 23
                        },
                        new
                        {
                            TeacherId = 104,
                            SubjectId = 23
                        },
                        new
                        {
                            TeacherId = 101,
                            SubjectId = 24
                        },
                        new
                        {
                            TeacherId = 104,
                            SubjectId = 24
                        },
                        new
                        {
                            TeacherId = 102,
                            SubjectId = 25
                        },
                        new
                        {
                            TeacherId = 104,
                            SubjectId = 25
                        },
                        new
                        {
                            TeacherId = 102,
                            SubjectId = 26
                        },
                        new
                        {
                            TeacherId = 104,
                            SubjectId = 26
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 27
                        },
                        new
                        {
                            TeacherId = 104,
                            SubjectId = 27
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 28
                        },
                        new
                        {
                            TeacherId = 104,
                            SubjectId = 28
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 29
                        },
                        new
                        {
                            TeacherId = 104,
                            SubjectId = 29
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 30
                        },
                        new
                        {
                            TeacherId = 104,
                            SubjectId = 30
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 31
                        },
                        new
                        {
                            TeacherId = 105,
                            SubjectId = 31
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 32
                        },
                        new
                        {
                            TeacherId = 105,
                            SubjectId = 32
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 33
                        },
                        new
                        {
                            TeacherId = 105,
                            SubjectId = 33
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 34
                        },
                        new
                        {
                            TeacherId = 105,
                            SubjectId = 34
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 35
                        },
                        new
                        {
                            TeacherId = 105,
                            SubjectId = 35
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 36
                        },
                        new
                        {
                            TeacherId = 105,
                            SubjectId = 36
                        },
                        new
                        {
                            TeacherId = 101,
                            SubjectId = 37
                        },
                        new
                        {
                            TeacherId = 105,
                            SubjectId = 37
                        },
                        new
                        {
                            TeacherId = 101,
                            SubjectId = 38
                        },
                        new
                        {
                            TeacherId = 105,
                            SubjectId = 38
                        },
                        new
                        {
                            TeacherId = 101,
                            SubjectId = 39
                        },
                        new
                        {
                            TeacherId = 105,
                            SubjectId = 39
                        },
                        new
                        {
                            TeacherId = 102,
                            SubjectId = 40
                        },
                        new
                        {
                            TeacherId = 105,
                            SubjectId = 40
                        },
                        new
                        {
                            TeacherId = 102,
                            SubjectId = 41
                        },
                        new
                        {
                            TeacherId = 105,
                            SubjectId = 41
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 42
                        },
                        new
                        {
                            TeacherId = 105,
                            SubjectId = 42
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 43
                        },
                        new
                        {
                            TeacherId = 105,
                            SubjectId = 43
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 44
                        },
                        new
                        {
                            TeacherId = 105,
                            SubjectId = 44
                        },
                        new
                        {
                            TeacherId = 100,
                            SubjectId = 45
                        },
                        new
                        {
                            TeacherId = 105,
                            SubjectId = 45
                        });
                });

            modelBuilder.Entity("MyBackendAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ResetPasswordOtp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetPasswordOtpExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasFilter("[StudentId] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "datvideo04@gmail.com",
                            FullName = "Phan Thanh Dat",
                            Password = "denhat123",
                            PhoneNumber = "0352578129",
                            StudentId = "ADMIN001"
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 1,
                            Email = "student3@fpt.edu.vn",
                            FullName = "Student 3 - 10A",
                            Password = "password123",
                            PhoneNumber = "0900000003",
                            StudentId = "STU00003"
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 1,
                            Email = "student4@fpt.edu.vn",
                            FullName = "Student 4 - 10A",
                            Password = "password123",
                            PhoneNumber = "0900000004",
                            StudentId = "STU00004"
                        },
                        new
                        {
                            Id = 5,
                            ClassId = 1,
                            Email = "student5@fpt.edu.vn",
                            FullName = "Student 5 - 10A",
                            Password = "password123",
                            PhoneNumber = "0900000005",
                            StudentId = "STU00005"
                        },
                        new
                        {
                            Id = 6,
                            ClassId = 2,
                            Email = "student6@fpt.edu.vn",
                            FullName = "Student 6 - 10A01",
                            Password = "password123",
                            PhoneNumber = "0900000006",
                            StudentId = "STU00006"
                        },
                        new
                        {
                            Id = 7,
                            ClassId = 2,
                            Email = "student7@fpt.edu.vn",
                            FullName = "Student 7 - 10A01",
                            Password = "password123",
                            PhoneNumber = "0900000007",
                            StudentId = "STU00007"
                        },
                        new
                        {
                            Id = 8,
                            ClassId = 2,
                            Email = "student8@fpt.edu.vn",
                            FullName = "Student 8 - 10A01",
                            Password = "password123",
                            PhoneNumber = "0900000008",
                            StudentId = "STU00008"
                        },
                        new
                        {
                            Id = 9,
                            ClassId = 3,
                            Email = "student9@fpt.edu.vn",
                            FullName = "Student 9 - 10D",
                            Password = "password123",
                            PhoneNumber = "0900000009",
                            StudentId = "STU00009"
                        },
                        new
                        {
                            Id = 10,
                            ClassId = 3,
                            Email = "student10@fpt.edu.vn",
                            FullName = "Student 10 - 10D",
                            Password = "password123",
                            PhoneNumber = "0900000010",
                            StudentId = "STU00010"
                        },
                        new
                        {
                            Id = 11,
                            ClassId = 3,
                            Email = "student11@fpt.edu.vn",
                            FullName = "Student 11 - 10D",
                            Password = "password123",
                            PhoneNumber = "0900000011",
                            StudentId = "STU00011"
                        },
                        new
                        {
                            Id = 12,
                            ClassId = 4,
                            Email = "student12@fpt.edu.vn",
                            FullName = "Student 12 - 11A",
                            Password = "password123",
                            PhoneNumber = "0900000012",
                            StudentId = "STU00012"
                        },
                        new
                        {
                            Id = 13,
                            ClassId = 4,
                            Email = "student13@fpt.edu.vn",
                            FullName = "Student 13 - 11A",
                            Password = "password123",
                            PhoneNumber = "0900000013",
                            StudentId = "STU00013"
                        },
                        new
                        {
                            Id = 14,
                            ClassId = 4,
                            Email = "student14@fpt.edu.vn",
                            FullName = "Student 14 - 11A",
                            Password = "password123",
                            PhoneNumber = "0900000014",
                            StudentId = "STU00014"
                        },
                        new
                        {
                            Id = 15,
                            ClassId = 5,
                            Email = "student15@fpt.edu.vn",
                            FullName = "Student 15 - 11A01",
                            Password = "password123",
                            PhoneNumber = "0900000015",
                            StudentId = "STU00015"
                        },
                        new
                        {
                            Id = 16,
                            ClassId = 5,
                            Email = "student16@fpt.edu.vn",
                            FullName = "Student 16 - 11A01",
                            Password = "password123",
                            PhoneNumber = "0900000016",
                            StudentId = "STU00016"
                        },
                        new
                        {
                            Id = 17,
                            ClassId = 5,
                            Email = "student17@fpt.edu.vn",
                            FullName = "Student 17 - 11A01",
                            Password = "password123",
                            PhoneNumber = "0900000017",
                            StudentId = "STU00017"
                        },
                        new
                        {
                            Id = 18,
                            ClassId = 6,
                            Email = "student18@fpt.edu.vn",
                            FullName = "Student 18 - 11D",
                            Password = "password123",
                            PhoneNumber = "0900000018",
                            StudentId = "STU00018"
                        },
                        new
                        {
                            Id = 19,
                            ClassId = 6,
                            Email = "student19@fpt.edu.vn",
                            FullName = "Student 19 - 11D",
                            Password = "password123",
                            PhoneNumber = "0900000019",
                            StudentId = "STU00019"
                        },
                        new
                        {
                            Id = 20,
                            ClassId = 6,
                            Email = "student20@fpt.edu.vn",
                            FullName = "Student 20 - 11D",
                            Password = "password123",
                            PhoneNumber = "0900000020",
                            StudentId = "STU00020"
                        },
                        new
                        {
                            Id = 21,
                            ClassId = 7,
                            Email = "student21@fpt.edu.vn",
                            FullName = "Student 21 - 12A",
                            Password = "password123",
                            PhoneNumber = "0900000021",
                            StudentId = "STU00021"
                        },
                        new
                        {
                            Id = 22,
                            ClassId = 7,
                            Email = "student22@fpt.edu.vn",
                            FullName = "Student 22 - 12A",
                            Password = "password123",
                            PhoneNumber = "0900000022",
                            StudentId = "STU00022"
                        },
                        new
                        {
                            Id = 23,
                            ClassId = 7,
                            Email = "student23@fpt.edu.vn",
                            FullName = "Student 23 - 12A",
                            Password = "password123",
                            PhoneNumber = "0900000023",
                            StudentId = "STU00023"
                        },
                        new
                        {
                            Id = 24,
                            ClassId = 8,
                            Email = "student24@fpt.edu.vn",
                            FullName = "Student 24 - 12A01",
                            Password = "password123",
                            PhoneNumber = "0900000024",
                            StudentId = "STU00024"
                        },
                        new
                        {
                            Id = 25,
                            ClassId = 8,
                            Email = "student25@fpt.edu.vn",
                            FullName = "Student 25 - 12A01",
                            Password = "password123",
                            PhoneNumber = "0900000025",
                            StudentId = "STU00025"
                        },
                        new
                        {
                            Id = 26,
                            ClassId = 8,
                            Email = "student26@fpt.edu.vn",
                            FullName = "Student 26 - 12A01",
                            Password = "password123",
                            PhoneNumber = "0900000026",
                            StudentId = "STU00026"
                        },
                        new
                        {
                            Id = 27,
                            ClassId = 9,
                            Email = "student27@fpt.edu.vn",
                            FullName = "Student 27 - 12D",
                            Password = "password123",
                            PhoneNumber = "0900000027",
                            StudentId = "STU00027"
                        },
                        new
                        {
                            Id = 28,
                            ClassId = 9,
                            Email = "student28@fpt.edu.vn",
                            FullName = "Student 28 - 12D",
                            Password = "password123",
                            PhoneNumber = "0900000028",
                            StudentId = "STU00028"
                        },
                        new
                        {
                            Id = 29,
                            ClassId = 9,
                            Email = "student29@fpt.edu.vn",
                            FullName = "Student 29 - 12D",
                            Password = "password123",
                            PhoneNumber = "0900000029",
                            StudentId = "STU00029"
                        },
                        new
                        {
                            Id = 100,
                            Email = "gv_bb@fpt.edu.vn",
                            FullName = "Giáo viên Bắt buộc",
                            Password = "password123",
                            PhoneNumber = "0333333100",
                            StudentId = "GVBB01"
                        },
                        new
                        {
                            Id = 101,
                            Email = "gv_tn@fpt.edu.vn",
                            FullName = "Giáo viên Tự nhiên",
                            Password = "password123",
                            PhoneNumber = "0333333101",
                            StudentId = "GVTN01"
                        },
                        new
                        {
                            Id = 102,
                            Email = "gv_xh@fpt.edu.vn",
                            FullName = "Giáo viên Xã hội",
                            Password = "password123",
                            PhoneNumber = "0333333102",
                            StudentId = "GVXH01"
                        },
                        new
                        {
                            Id = 103,
                            Email = "gv_khoi10@fpt.edu.vn",
                            FullName = "Giáo viên Khối 10",
                            Password = "password123",
                            PhoneNumber = "0333333103",
                            StudentId = "GVK10"
                        },
                        new
                        {
                            Id = 104,
                            Email = "gv_khoi11@fpt.edu.vn",
                            FullName = "Giáo viên Khối 11",
                            Password = "password123",
                            PhoneNumber = "0333333104",
                            StudentId = "GVK11"
                        },
                        new
                        {
                            Id = 105,
                            Email = "gv_khoi12@fpt.edu.vn",
                            FullName = "Giáo viên Khối 12",
                            Password = "password123",
                            PhoneNumber = "0333333105",
                            StudentId = "GVK12"
                        });
                });

            modelBuilder.Entity("MyBackendAPI.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 9,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 10,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 11,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 12,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 13,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 14,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 15,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 16,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 17,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 18,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 19,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 20,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 21,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 22,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 23,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 24,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 25,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 26,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 27,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 28,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 29,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 100,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 101,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 102,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 103,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 104,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 105,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("MyBackendAPI.Models.Grade", b =>
                {
                    b.HasOne("MyBackendAPI.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyBackendAPI.Models.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyBackendAPI.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("MyBackendAPI.Models.Notification", b =>
                {
                    b.HasOne("MyBackendAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyBackendAPI.Models.Schedule", b =>
                {
                    b.HasOne("MyBackendAPI.Models.Class", "Class")
                        .WithMany("Schedules")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyBackendAPI.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyBackendAPI.Models.User", "Teacher")
                        .WithMany("Schedules")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Room");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("MyBackendAPI.Models.ScheduleRequest", b =>
                {
                    b.HasOne("MyBackendAPI.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyBackendAPI.Models.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("MyBackendAPI.Models.TeacherSubject", b =>
                {
                    b.HasOne("MyBackendAPI.Models.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyBackendAPI.Models.User", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("MyBackendAPI.Models.User", b =>
                {
                    b.HasOne("MyBackendAPI.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Class");
                });

            modelBuilder.Entity("MyBackendAPI.Models.UserRole", b =>
                {
                    b.HasOne("MyBackendAPI.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyBackendAPI.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyBackendAPI.Models.Class", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("MyBackendAPI.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MyBackendAPI.Models.Subject", b =>
                {
                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("MyBackendAPI.Models.User", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("TeacherSubjects");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
